version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: loan_request_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  loanrequest:
    build: ../.
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis